# Generated by Django 2.1.4 on 2018-12-06 09:12

import datetime
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    def create_data(apps, schema_editor):
        User = apps.get_model(settings.AUTH_USER_MODEL)
        user = User(pk=1, username="auth0user", is_active=True, email="myemail@someprovider.com")
        user.save()

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=50)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(default=datetime.date.today)),
            ],
            options={
                'db_table': 'task',
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(create_data)
    ]
